// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtmb0W2bncyaQLx605jNV2eRP1R9A0vU',
    appId: '1:520370134301:web:9462c1130f897485ee55f4',
    messagingSenderId: '520370134301',
    projectId: 'form-20621',
    authDomain: 'form-20621.firebaseapp.com',
    storageBucket: 'form-20621.appspot.com',
    measurementId: 'G-W5PM4QN74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfvI_IesO9uUrXop2-h61WaBBrmBXJNi4',
    appId: '1:520370134301:android:1b2fdc5d31ae6c52ee55f4',
    messagingSenderId: '520370134301',
    projectId: 'form-20621',
    storageBucket: 'form-20621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YE8Bd2dzDo5Xa1YgmPN0HZuvM0dy_Hk',
    appId: '1:520370134301:ios:bf1ab3d4f2304b96ee55f4',
    messagingSenderId: '520370134301',
    projectId: 'form-20621',
    storageBucket: 'form-20621.appspot.com',
    androidClientId: '520370134301-0i9enpua2s1565bhvlg8tqdn6nop4o9a.apps.googleusercontent.com',
    iosClientId: '520370134301-sogh86bpko3vlk7c1ilop78h2fdus50i.apps.googleusercontent.com',
    iosBundleId: 'com.monty.form',
  );
}
